/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Product {
  'id' : bigint,
  'imgPath' : string,
  'originalMrp' : bigint,
  'owner' : Principal,
  'name' : string,
  'tags' : [] | [Array<string>],
  'shortDescription' : string,
  'brand' : string,
  'discountedPrice' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      string,
      bigint,
      bigint,
      [] | [Array<string>],
    ],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyProducts' : ActorMethod<[], Array<Product>>,
  'getProduct' : ActorMethod<[bigint], Product>,
  'getProductDetails' : ActorMethod<[bigint], Product>,
  'getProductsByBrand' : ActorMethod<[string], Array<Product>>,
  'getProductsGroupedByBrand' : ActorMethod<
    [],
    Array<[string, Array<Product>]>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateProduct' : ActorMethod<
    [
      bigint,
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [bigint],
      [] | [bigint],
      [] | [Array<string>],
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];